server:
  port: 8081

logging:
  level:
    org.springframework.security: ERROR

spring:
  jackson:
    serialization-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  data:
    mongodb:
      host: ask.dog
      database: askdog-coupon


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
feign:
  hystrix:
    enabled: false

askdog:
  security:
    oauth2:
      client:
        client-id: askdog-coupon-store
        client-secret: GnkW*!shY8+eOM
        access-token-uri: http://localhost:8080/oauth/token
        user-authorization-uri: http://localhost:8080/oauth/authorize
        scope: trusted
      resource:
        user-info-uri: http://localhost:8080/oauth/userinfo
