server:
  port: ${ASK_DOG_SERVER_PORT:9001}
spring:
  jackson:
    serialization-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  cloud:
    stream:
      bindings:
        event:
          destination: topic.event
          group: messaging-logging
      kafka:
        bindings:
          event:
            consumer:
              start-offset: earliest
        binder:
          brokers: dev.ask.dog
          zkNodes: dev.ask.dog
