version: '2'

services:
  postgres:
    container_name: postgres
    build: ./docker/build/postgres
    image: ad-postgres
    environment:
      - POSTGRES_PASSWORD=mgr.dog@xsO2OkmYW1
      - PGDATA=/var/lib/postgresql/data/ask.dog
    volumes:
      - $PWD/docker/volume/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  elasticsearch:
    container_name: elasticsearch
    #build: ./docker/build/elasticsearch
    image: elasticsearch:2.3.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - $PWD/docker/volume/elasticsearch/config:/usr/share/elasticsearch/config
      - $PWD/docker/volume/elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana
    build: ./docker/build/kibana
    image: ad-kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
